### ISSUE TITLE
🖇 이건 무슨 의미인가요?

### ISSUE THREAD

**Issue by kiljh-me** [O-O-wl/TIL#1]
포크해서 쓰고 있는데요.

결과에서 🖇 모양이 무슨 뜻으로 쓰셨는지 궁금해서요.

**Comment by O-O-wl** [comment]
보류입니다! 내일로 미루는 거지여 ㅎㅎ
X는 잘못생각한 거라 삭제 같은 개념을 사용하고 있습니다 ~
